#   Profile
#   - Different configuration profiles may be encoded here to be specified
	#   as parameters to the configtxgen too
	#
################################################################################
Profiles:
    TwoOrgsOrdererGenesis: # Orderer 节点的创世块的信息
        Orderer:
            <<: *OrdererDefaults # 引用 OrdererDefaults 的内容
            Organizations:
                - *OrdererOrg # 参与的 Orderer 节点的配置，引用 OrdererOrg 内容

        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Org1 # 参与的组织，引用 Org1 内容
                    - *Org2 # 参与的组织，引用 Org2 内容
    TwoOrgsChannel: # 用来创建新链，包含参与新链的组织
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults # 引用 ApplicationDefaults 的内容
            Organizations:
                - *Org1 # 新链的参与组织，引用 Org1 的内容
                - *Org2 # 新链的参与组织，引用 Org2 的内容

################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # SampleOrg defines an MSP using the sampleconfig.  It should never be used
    # in production but may be used as a template for other definitions
    - &OrdererOrg # Orderer 节点的 msp 配置
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrdererOrg1 # Orderer 节点 msp 名称

        # ID to load the MSP definition as

        ID: OrdererMSP1 #Orderer节点的 msp id

        # Orderer节点 MSP 目录
        MSPDir: ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp

    - &Org1 #组织 1 的 msp 配置信息
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org1MSP # 组织 1 的 msp 名称
        # ID to load the MSP definition as
        ID: Org1MSP # 组织 1 的 msp id
       #组织1的MSP目录
        MSPDir: ./crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
	
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
	          # 通过 gossip 跨组织同步信息
            - Host: peer0.org1.example.com
              Port: 7051

    - &Org2
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: Org2MSP

        # ID to load the MSP definition as
        ID: Org2MSP

        MSPDir: ./crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org2.example.com
              Port: 7051
################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: kafka # 共识的类型，目前支持 solo, kafka, sbft
    Addresses:
        - 127.0.0.1:56050 # Orderer 节点的 IP，如果采用联机模式，则需要配置为 orderer_ip:orderer_port 这样的形式，如本机的 ip 为 172.16.1.9，那么此处得修改为 172.16.1.9:56050，如果有多个 orderer 节点，则需要在 Addresses 字段里配置多个 Orderer 节点的 ip:port，每个 Orderer 节点 ip:port 前面都加上 - 符号，并且每个 Orderer 配置独立一行。

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s # 生成一个 block 的间隔

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 500 # 单个区块中包含的最大交易数
        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 98 MB # 单个 block 的最大字节数

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092 # Kafka 地址，如果采用联机模式，则需要配置 Kafka所在主机的 ip:port。如本机为 172.16.1.9，则此处需配置为 172.16.1.9:9092。如果 Kafka 集群有多个 Kafka 节点，则此处需要配置每个 Kafka 节点的 ip:port。每个 Kafka 节点的配置独立一行且以 - 符号开头。

    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:
